baseURL = "https://helloworld.aworkshop.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "AWS Lake Formation Workshop"
theme = "learn"
uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
themeVariant = "mine"
showVisitedLinks = false
description = "AWS Lake Formation Workshop"
disableSearch = false
disableAssetsBusting = true
disableLanguageSwitchingButton = true
disableShortcutsTitle = true

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]

[markup]
  defaultMarkdownHandler = "blackFriday"
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
